// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAer9IS9cxncIPnq2DYXgNI1hE4LV2D4Fo',
    appId: '1:491153662164:web:361530c5200aafe44f1b41',
    messagingSenderId: '491153662164',
    projectId: 'marine-bebop-361716',
    authDomain: 'marine-bebop-361716.firebaseapp.com',
    storageBucket: 'marine-bebop-361716.appspot.com',
    measurementId: 'G-ZSTCX5Z83S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_JzZ8GlvbuWpFVgN84Nqbn9TSzXfzZtE',
    appId: '1:491153662164:android:d38843e0360bb18b4f1b41',
    messagingSenderId: '491153662164',
    projectId: 'marine-bebop-361716',
    storageBucket: 'marine-bebop-361716.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEN_SDFg1zcqLyZy3R2fpM5Qo9CKP2eAk',
    appId: '1:491153662164:ios:9965253877829efa4f1b41',
    messagingSenderId: '491153662164',
    projectId: 'marine-bebop-361716',
    storageBucket: 'marine-bebop-361716.appspot.com',
    androidClientId: '491153662164-4rjr9nptaj7jiumans0mej2ksjbj4568.apps.googleusercontent.com',
    iosClientId: '491153662164-dedlvmsduklird47k103ehv3kdv23f60.apps.googleusercontent.com',
    iosBundleId: 'com.Macradev.accounts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEN_SDFg1zcqLyZy3R2fpM5Qo9CKP2eAk',
    appId: '1:491153662164:ios:9965253877829efa4f1b41',
    messagingSenderId: '491153662164',
    projectId: 'marine-bebop-361716',
    storageBucket: 'marine-bebop-361716.appspot.com',
    androidClientId: '491153662164-4rjr9nptaj7jiumans0mej2ksjbj4568.apps.googleusercontent.com',
    iosClientId: '491153662164-dedlvmsduklird47k103ehv3kdv23f60.apps.googleusercontent.com',
    iosBundleId: 'com.Macradev.accounts',
  );
}
